<a href="https://colab.research.google.com/github/tulaycelenk/IntroToMachineLearning/blob/main/Week2-homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [5]:
array2=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(array2.shape)

(15,)


In [6]:
#matrix reshaping
a=array2.reshape(3,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [7]:
#matrix shape
print("shape: ",a.shape)

shape:  (3, 5)


In [8]:
#matrix dimention
print("dimention:",a.ndim)

dimention: 2


In [9]:
#matrix data type a.dtype
print("data type:",a.dtype)

data type: int64


In [10]:
#matrix size
print("size:",a.size)

size: 15


In [11]:
print("type:",type(a))

type: <class 'numpy.ndarray'>


In [12]:
array3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [13]:
print(array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
array3.shape


(3, 4)

In [15]:
zeros=np.zeros((3,4))

In [16]:
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:

#zeros[0,0]=5
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
ones=np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
empty=np.empty((4,5))
print(empty)

[[0.  0.  0.3 1.  0. ]
 [0.  1.  1.  1.  1. ]
 [1.  1.  1.  0.  0. ]
 [1.  0.5 0.  0.  1. ]]


In [20]:
#from 10 to 150 5 by 5
np.arange(10,150,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
       140, 145])

In [21]:
#from 10 to 150 5 by 5
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [22]:
m=np.array([1,2,3])
k=np.array([4,5,6])

print(m+k)
print(m-k)
print(m**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [23]:
list = [1,2,3,4]
array=np.array([1,2,3,4])
print(list)
print(array)

[1, 2, 3, 4]
[1 2 3 4]


In [24]:
x=np.array([9,8,7])
y=x
z=y
print(x)
print("----")
print(y)
print("----")
print(z)

[9 8 7]
----
[9 8 7]
----
[9 8 7]


In [25]:
q=x.copy()
print(q)

[9 8 7]


In [26]:
#from first row to second 
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
a[::-1]

array([[11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [28]:
b=np.array([[1,2,3,4,5,6,7],[8,9,11,22,33,44,55]])
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 11, 22, 33, 44, 55]])

In [29]:
#all columns first row
print(b[1,:])

[ 8  9 11 22 33 44 55]


In [30]:
#starts from beginning
print(b[-1,:])

[ 8  9 11 22 33 44 55]


In [31]:
#transform array to one dimentional version
b=b.ravel()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 22, 33, 44, 55])

In [32]:
#transpose
b.T
print(b)

[ 1  2  3  4  5  6  7  8  9 11 22 33 44 55]
