<a href="https://colab.research.google.com/github/tulaycelenk/IntroToMachineLearning/blob/main/Week2-homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [ ]:
array2= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(array2.shape)

(15,)


In [ ]:
reshaped = array2.reshape(3,5)
print(reshaped)

#gives row and column
print(reshaped.shape)

#gives dimension
print(reshaped.ndim)

#gives type name
print(reshaped.dtype.name)

#gives size
print(reshaped.size)

#gives dimension
print(reshaped.ndim)

#gives type in python
print(type(reshaped))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
2
int64
15
2
<class 'numpy.ndarray'>


In [ ]:
array4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array4)
print(array4.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
zeros = np.zeros((3,5))
print(zeros)

ones = np.ones((3,5))
ones[0,0] = 5
print(ones)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
emptyArray = np.empty((3,3))
print(emptyArray)

[[2.88230704e-316 0.00000000e+000 6.94822232e-310]
 [6.94822232e-310 6.94822232e-310 6.94822232e-310]
 [6.94822232e-310 6.94816005e-310 1.18575755e-321]]


In [ ]:
#from 5 to 40 by increasing 5 each time
np.arange(5,40,5)

array([ 5, 10, 15, 20, 25, 30, 35])

In [ ]:
#between 0 and 10, it gives 20 values
np.linspace(0,10,20)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
array5 = np.array([1,2,3])
array6 = np.array([4,5,6])
print(array5+array6)
print(array5-array6)
print(array5**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [ ]:
array7 = np.array([1,2,3])
array8 = array7
array9 = array8

array9[0] = 90
print(array7,array8,array9)

[90  2  3] [90  2  3] [90  2  3]


In [ ]:
array10 = array9.copy()
print(array10)
array10[0]=101
print(array7,array8,array9,array10)

[90  2  3]
[90  2  3] [90  2  3] [90  2  3] [101   2   3]


In [ ]:
array11 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array11)
print(array11[1,1])
print(array11[:,2])
print(array11[0,:])
print(array11[1,1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[3 8]
[1 2 3 4 5]


In [28]:
b=np.array([[1,2,3,4,5,6,7],[8,9,11,22,33,44,55]])
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 11, 22, 33, 44, 55]])

In [29]:
#all rows first column
print(b[:,1])

[2 9]


In [30]:
#all columns first row
print(b[1,:])

[ 8  9 11 22 33 44 55]


In [31]:
#starts from beginning
print(b[-1,:])

[ 8  9 11 22 33 44 55]


In [33]:
#transform array to one dimentional version
b=b.ravel()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 22, 33, 44, 55])

In [36]:
#transpose
b.T
print(b)

[ 1  2  3  4  5  6  7  8  9 11 22 33 44 55]
